export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILED = 'ADD_EVENT_FAILED';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_FAILED = 'LOAD_EVENTS_FAILED';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const BOOK_DAY = 'BOOK_DAY';
export const BOOK_HOUR = 'BOOK_HOUR';